name: Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
  DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5432/${{ secrets.DB_NAME }}?schema=public

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -t $IMAGE .

      - name: Push the docker image to Container Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy ${{ secrets.SERVICE_NAME }}
          --image $IMAGE
          --port ${{ secrets.PORT }}
          --project ${{ secrets.GCP_PROJECT_ID }}
          --region ${{ secrets.GCP_REGION }}
          --platform=managed
          --add-cloudsql-instances ${{ secrets.DB_INSTANCE }}
          --min-instances=1
          --quiet
          --set-env-vars DATABASE_URL=$DATABASE_URL
          --set-env-vars HOST_URI="${{ secrets.HOST_URI }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_TYPE="${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYPE }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_PROJECT_ID="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_ID }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL="${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_CLIENT_ID="${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_ID }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_AUTH_URI="${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_URI }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_TOKEN_URI="${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN_URI }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL="${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL }}"
          --set-env-vars FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL="${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}"
